apiVersion: v1
kind: Service
metadata:
  name: the-wall
  labels:
    app: the-wall
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: the-wall
