apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg
spec:
  template:
    metadata:
      name: pg
      labels:
        app: pg
    spec:
      containers:
        - name: pg
          image: postgres:15.4
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: postgres
          startupProbe:
            initialDelaySeconds: 15
            exec:
              command:
                - pg_isready
          command:
            - postgres
            - -c
            - max_connections=15
  selector:
    matchLabels:
      app: pg
  replicas: 1
