apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pg
  template:
    metadata:
      name: pg
      labels:
        app: pg
    spec:
      automountServiceAccountToken: false
      containers:
        - name: pg
          image: 'postgres:15'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: postgres
          resources:
            limits:
              memory: 100Mi
              cpu: 500m