apiVersion: v1
kind: Service
metadata:
  name: business-manager
  labels:
    app: business-manager
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: business-manager
