apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs
  labels:
    app: docs
spec:
  selector:
    matchLabels:
      app: docs
  template:
    metadata:
      labels:
        app: docs
    spec:
      automountServiceAccountToken: false
      containers:
        - name: docs
          image: "ghcr.io/meysambavi/docs:38"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - mountPath: /etc/config
              name: config
          resources:
            limits:
              memory: 100Mi
              cpu: 500m
      volumes:
        - name: config
          configMap:
            name: docs
      imagePullSecrets:
        - name: ghcr.secret
