apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway
data:
  nginx.conf: |
    events {}
    http {
        server {
            listen 80;
            server_name 0.0.0.0;

            location /api/auth/ {
                proxy_pass http://the-wall/;
            }

            location = /api/auth/test {
                auth_request /api/auth/authenticate;
                proxy_pass http://the-wall/test;
            }

            location / {
                proxy_pass http://frontend/;
            }
        }

        upstream the-wall {
            server the-wall;
        }

        upstream frontend {
            server frontend;
        }
    }
