apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      automountServiceAccountToken: false
      containers:
        - name: gateway
          image: "nginx"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - mountPath: /etc/nginx
              name: config
          resources:
            limits:
              memory: 100Mi
              cpu: 500m
      volumes:
        - name: config
          configMap:
            name: gateway
      imagePullSecrets:
        - name: ghcr.secret
