apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      nodePort: 30003
      targetPort: 80
  selector:
    app: gateway
