name: Build and Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Validate PR Title
        uses: amannn/action-semantic-pull-request@v5.5.2
        id: pr_title
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          requireScope: true
      - name: Identify Build Target
        id: build_info
        working-directory: "."
        run: |
          run_number="${{ github.run_number }}"
          scope="${{ steps.pr_title.outputs.scope }}"
          event="${{ github.event_name }}"
          
          if [ -z "$scope" ]; then
              echo "scope variable is not set" >&2
              exit 1
          fi
          
          context=""
          file=""
          tag=""
          tag_prefix="ghcr.io/meysambavi/"
          if [ "$event" = "push" ]; then  
            tag="$tag_prefix$scope:$run_number,$tag_prefix$scope:latest"
          else
            tag="$tag_prefix$scope:beta-$run_number"
          fi
          
          if [ "$scope" = "frontend" ]; then
              context="./frontend/appointment-scheduler"
              file="./frontend/appointment-scheduler/Dockerfile"
          else
              context="."
              file="./backend/src/$scope/Dockerfile"
          fi
                    
          echo "context=$context" >> "$GITHUB_OUTPUT"
          echo "file=$file" >> "$GITHUB_OUTPUT"
          echo "tag=$tag" >> "$GITHUB_OUTPUT"
          
          echo "build context: $context"
          echo "Dockerfile path: $file"
          echo "image tag: $tag"
          
          exit 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and export
        uses: docker/build-push-action@v5.3.0
        with:
          context: ${{ steps.build_info.outputs.context }}
          tags: ${{ steps.build_info.outputs.tag }}
          file: ${{ steps.build_info.outputs.file }}
          push: true
