name: Deploy
on:
  push:
    branches: [ "deploy", "add-ci-cd" ]
jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Execute ssh to apply changes
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            set -e
            branch="add-ci-cd"
            cd ~/appointment-scheduler
            git checkout "$branch"
            git fetch --all
            git reset --hard origin/"$branch"
            git pull
            cd deployment
            for d in */ ; do
              kubectl apply -f "$d"
            done