name: Test and Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Validate PR Title
        uses: amannn/action-semantic-pull-request@v5
        id: pr_title
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            
      - name: Identify Build Target
        id: build_info
        working-directory: "."
        env:
          SCOPE: ${{ steps.pr_title.outputs.scope }}
          RUN_NUMBER: ${{ github.run_number }}
        run: |
          scope="$SCOPE"
          run_number=$(( ${RUN_NUMBER:-0} * 100 + RANDOM % 100 ))
          
          if [ -z "$scope" ]; then
              echo "scope variable is not set" >&2
              exit 1
          fi
          
          context=""
          path=""
          tag=""
          
          if [ "$scope" = "frontend" ]; then
              context="./frontend/appointment-scheduler"
              path="./Dockerfile"
              tag="frontend:$run_number"
          else
              context="."
              path="./backend/src/$scope/Dockerfile"
              tag="$scope:$run_number"
          fi
          
          echo "context=$context" >> "$GITHUB_OUTPUT"
          echo "path=$path" >> "$GITHUB_OUTPUT"
          echo "tag=ghcr.io/meysambavi/$tag" >> "$GITHUB_OUTPUT"
          
          exit 0
      
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and export
        uses: docker/build-push-action@v5
        with:
          context: ${{ steps.build_info.outputs.context }}
          tags: ${{ steps.build_info.outputs.tag }}
          file: ${{ steps.build_info.outputs.file }}
          push: true
